# Generated by Django 5.1.5 on 2025-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIMain', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
